### ISSUE TITLE
"severity levels" link generates 404

### ISSUE THREAD

**Issue by djhair01jds** [PagerDuty/incident-response-docs#115]
The link "severity levels" references "https://github.com/PagerDuty/incident-response-docs/blob/master/before/severity_levels.md" which appears to be missing.

![image](https://user-images.githubusercontent.com/25917760/103038753-3e91db80-453d-11eb-88bc-e936e21750b5.png)

**Comment by richadams** [comment]
https://github.com/PagerDuty/incident-response-docs/pull/122 will fix this I think.

**Comment by richadams** [comment]
This should now be fixed.
