### ISSUE TITLE
Scribe link in Getting Started broken/404

### ISSUE THREAD

**Issue by ElijahLynn** [PagerDuty/incident-response-docs#135]
https://response.pagerduty.com/getting_started/before/different_roles#scribe
https://response.pagerduty.com/getting_started/#add-a-scribe-if-you-havent-already
https://github.com/PagerDuty/incident-response-docs/blob/master/docs/getting_started.md

![image](https://github.com/PagerDuty/incident-response-docs/assets/1504756/0e82074c-efe8-4849-8d9c-70bff91b5870)
![image](https://github.com/PagerDuty/incident-response-docs/assets/1504756/9adf1351-3e4e-41d1-8e28-46695646f8bc)

**Comment by lnxchk** [comment]
Thanks! Fixed in PR 137
