### ISSUE TITLE
management of the !status stalk bot

### ISSUE THREAD

**Issue by gurretp** [PagerDuty/incident-response-docs#24]
The management of the "!status stalk" bot is assigned to either the scribe or the deputy depending on which document we look at :
- docs/training/scribe.md  line 50 (task assigned to the scribe)
- docs/during/during_an_incident.md  line 73 (task assigned to the deputy)

**Comment by esigler** [comment]
Good catch!  This evolved a bit internally - the scribe takes care of this now more than the deputy. I'll send a PR to update the docs.

**Comment by richadams** [comment]
Nice find, this is left over from when our Deputy and Scribe roles were one and the same. When we split them out into different roles, I must have updated the tasks in one area, but not the other.
