### ISSUE TITLE
mkdocs server throws an error

### ISSUE THREAD

**Issue by rommeltinoco** [PagerDuty/incident-response-docs#62]
INFO    -  Building documentation...
WARNING -  The theme 'material' does not appear to have a configuration file. Please upgrade to a current version of the theme.
WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs.
WARNING -  Config value: 'site_favicon'. Warning: Unrecognised configuration name: site_favicon
INFO    -  Cleaning site directory
ERROR   -  Error building page index.md

main.html

Upgrading the them does not fix the error

and looks like its related to:
https://github.com/squidfunk/mkdocs-material/issues/519

**Comment by richadams** [comment]
D'oh, I "fixed" this by pinning to version 0.15.3 in our CI toolchain (https://github.com/PagerDuty/incident-response-docs/blob/master/circle.yml#L8), but didn't update our README accordingly. Will do that now!

**Comment by richadams** [comment]
Latest update to the README should get this working for you again. Sorry about that! Thanks for reporting.
