### ISSUE TITLE
re: "Did it show up in canary?"

### ISSUE THREAD

**Issue by stig** [PagerDuty/incident-response-docs#7]
This comment is from this page: https://response.pagerduty.com/after/post_mortem_process/

I'm just wondering what this "canary" you refer to is? I'm assuming an internal system, in the canary down the coalmine sense, but would love a clarification.

PS: I love this resource.

**Comment by richadams** [comment]
It isn't an internal system, but rather one of the testing methods we use before changes are fully deployed to production. Essentially deploying changes to a small subset of nodes and sending a small amount of traffic there to validate the changes before they get the full release.

The idea being that if there's a breaking change, the canary hosts would raise errors, and only a small amount of traffic would be affected.

We talk more about it in [this blog post](https://www.pagerduty.com/blog/continuous-build-break-fix-fast/), and the following quote sums it up well.

> In a canary release you have one or more new releases of the application in parallel to the existing production version. Once the release(es) are complete, you divert all or sub-segments of traffic from production to the new release environments. The purpose of sub-segments is to do A/B testing on slight variations of the releases.

PS: Thanks!
